spring.application.name=Assignment1

openai.transcription.url=https://api.openai.com/v1/audio/transcriptions
openai.transcription.model=gpt-4o-mini-transcribe

management.endpoint.shutdown.access=unrestricted
management.endpoints.web.exposure.include=shutdown